services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - starheroes_instance:/starheroes/instance
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    env_file: .env

volumes:
  starheroes_instance: